package org.webpagetest.dt2har.protocol;

import org.json.simple.JSONObject;

/**
 * A Devtools message indicating that a frame has been navigated.
 * This message does not appear in the protocol documentation, see:
 * https://developers.google.com/chrome-developer-tools/docs/protocol/1.0/page,
 * but is generated by Chrome nonetheless.
 *
 * <pre>
 * {
 *   "method":"Page.frameNavigated",
 *   "params":{
 *     "frame":{
 *       ...
 *     }
 *   }
 * }
 * </pre>
 */
public class PageFrameNavigatedMessage extends DevtoolsEventMessage {

  /** A description of the frame that was navigated. */
  protected JSONObject frame;

  /**
   * Construct a PageFrameNavigatedMessage.
   *
   * @param message The JSON-encoded message
   */
  PageFrameNavigatedMessage(JSONObject message) {
    super (message);
    // TODO: Parse complete message when
    // https://code.google.com/p/chromium/issues/detail?id=150602 is resolved.
    if (params.containsKey("frame")) {
      frame = (JSONObject) params.get("frame");
    }
  }

  /** Returns information about the frame that was navigated. */
  public JSONObject getFrame() {
    return frame;
  }
}
