<div class="tri-col feature-callouts">
                <div>
                    <img src="/images/real-experience-icon.svg" alt="">
                    <h2 class="alt">Real Experience</h2>
                    <p>Test your user’s real experience with global locations, modern devices, and the latest browser versions.</p>
                </div>
                <div>
                    <img src="/images/video-capture-icon.svg" alt="">
                    <h2 class="alt">Video Capture</h2>
                    <p>Correlate your user’s visual experience to the technical measurements of your site.</p>
                </div>
                <div>
                    <img src="/images/indepth-metrics-icon.svg" alt="">
                    <h2 class="alt">In-Depth Metrics</h2>
                    <p>Dive into the anatomy of your webpage with components like DNS, TCP, TLS, and more.</p>
                </div>
            </div>
            <figure class="testimonial">
                <blockquote>
                    <p>“WebPageTest makes our lives much easier at Catchpoint by letting us quickly test any URL from a wide array of locations. And it’s free!”</p>
                </blockquote>
                <figcaption><cite>Dritan Suljoti, Chief of Product at Catchpoint</cite></figcaption>
            </figure>
            <h2 class="light">Featured Content</h2>
            <div class="tri-col">
                <div class="resource-block">
                    <img src="/images/blog-placeholder.jpg" alt="">
                    <h3>Core Web Vitals are coming to a search algorithm near you</h3>
                    <p>Run a free website speed test from multiple locations around the globe using real browsers (IE and Chrome) and at real consumer connection speeds</p>
                </div>
                <div class="resource-block">
                    <img src="/images/blog-placeholder.jpg" alt="">
                    <h3>Core Web Vitals are coming to a search algorithm near you</h3>
                    <p>Run a free website speed test from multiple locations around the globe using real browsers (IE and Chrome) and at real consumer connection speeds</p>
                </div>
                <div class="resource-block">
                    <img src="/images/blog-placeholder.jpg" alt="">
                    <h3>Core Web Vitals are coming to a search algorithm near you</h3>
                    <p>Run a free website speed test from multiple locations around the globe using real browsers (IE and Chrome) and at real consumer connection speeds</p>
                </div>
            </div>