<?php 
$page_keywords = array('Access Denied','Blocked','Webpagetest','Website Speed Test','Page Speed');
$page_description = "Website speed test blocked.";
?>
<!DOCTYPE html>
<html>
    <head>
        <title>WebPagetest - Test Blocked</title>
        <?php $gaTemplate = 'Blocked'; include ('head.inc'); ?>
    </head>
    <body>
        <div class="page">
            <?php
            include 'header.inc';
            ?>

            <div class="translucent">
                <h1>Test Blocked</h1>
                <p>Sorry, but your test was blocked as part of our anti-abuse system.  There are some domains that we do not allow testing of to prevent use of the system to inflate page/video views or to drive traffic to sites where revenue is generated by impression.</p>
                <p><?php if($settings['contact']) echo 'If there is a site you want tested that was blocked, please <a href="mailto:' . $settings['contact'] . '">contact us</a>'. ' and send us your IP address (below) and URL that you are trying to test'; ?>.</p>
                <p>
                Your IP address: <b><?php echo $_SERVER['REMOTE_ADDR']; ?></b><br>
                URL Tested: <b><?php echo htmlspecialchars($url); ?></b><br>
                </p>
            </div>

            <?php include('footer.inc'); ?>
        </div>
    </body>
</html>
