// wptbho.idl : IDL source for wptbho
//

// This file will be processed by the MIDL tool to
// produce the type library (wptbho.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(C5D3C049-E67F-404D-A7BA-25A4580F11A2),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IWptBHO : IDispatch{
};
[
	uuid(24211012-D5F5-4827-8659-32E419A0D29B),
	version(1.0),
]
library wptbhoLib
{
	importlib("stdole2.tlb");
	[
		uuid(2B925455-8D0C-401F-AA4C-9336C2167F14)		
	]
	coclass WptBHO
	{
		[default] interface IWptBHO;
	};
};

