<?php
$MetricThresholds = array(
    'TTBF_POOR' => 2000,
    'TTBF_OK' => 1000,
    'FCP_POOR' => 5000,
    'FCP_OK' => 2000,
    'LCP_POOR' => 4000,
    'LCP_OK' => 2500,
    'CLS_POOR' => 0.25,
    'CLS_OK' => 0.1,
    'TBT_POOR' => 600,
    'TBT_OK' => 200,
    'RenderBlockingContentSizeCheck' => 0.5,
    'RenderBlockingContentPercentCheck' => 1,
    'RenderBlockingThirdPartyRequestsCheck' => 2
);
